version: "3.8"

services:
  db:
    image: postgres:12.3
    container_name: elixir_google_scraper_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=elixir_google_scraper_dev
    ports:
      - "5432:5432"
